### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by thebearingedge** [thebearingedge/code-container#1]
- [x] test for missing workspace folder
- [x] set up default dev user for mysql
- [x] add pgweb
- [x] ~look into adminer for mysql https://www.adminer.org/~
- [x] add docker-compose
- [x] set up a build/release pipeline on circleci / ~aws~ dockerhub
